### ISSUE TITLE
Show percentages for different classifications?

### ISSUE THREAD

**Issue by ghost** [winkjs/wink-naive-bayes-text-classifier#6]
Is there a way to currently do this or does it not yet exist?

**Comment by sanjayaksaxena** [comment]
The `predict()` method has the complete **sorted** list of different classifications, but it only returns the top classification as of now. This can be very easily added by returning the **`allOdds`** variable, instead of returning only the top value! You may like to make this modification in your fork/download.

We are also considering to release this as a feature shortly!

**Comment by sanjayaksaxena** [comment]
A new API **`computeOdds()`** has been released to address this need.
